security:
    enable_authenticator_manager: true

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto
        App\Entity\InternalUser:
            algorithm: auto

    role_hierarchy:
        ROLE_EMPLOYEE: [ ROLE_USER ]
        ROLE_MANAGER: [ ROLE_EMPLOYEE ]
        ROLE_OWNER: [ ROLE_MANAGER ]
        ROLE_ADMIN: [ ROLE_OWNER ]
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        sndit_app_user_provider:
            entity:
                class: App\Entity\User
        sndit_app_internal_user_provider:
            entity:
                class: App\Entity\InternalUser

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:   ^/api/login
            stateless: true
            provider:    sndit_app_user_provider
            custom_authenticators:
                - App\Security\CustomAuthenticator
            json_login:
                username_path:   phoneNumber
                check_path:      sndit_api_login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:     ^/api
            stateless:   true
            entry_point: jwt
            provider:    sndit_app_user_provider
            json_login:
                username_path:   phoneNumber
                check_path:      sndit_api_login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            jwt:
                authenticator: app.custom_authenticator
            refresh_jwt:
                check_path: /api/token/refresh

        internal_login:
            pattern:   ^/internal/api/login
            stateless: true
            provider:    sndit_app_internal_user_provider
            custom_authenticators:
                - App\Security\CustomInternalAuthenticator
            json_login:
                username_path:   email
                check_path:      sndit_internal_api_login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        internal_api:
            pattern:     ^/internal/api
            stateless:   true
            entry_point: jwt
            provider:    sndit_app_internal_user_provider
            json_login:
                username_path:   email
                check_path:      sndit_internal_api_login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            jwt: ~
            refresh_jwt:
                check_path: /api/token/refresh

    access_control:
        - { path: ^/api/token/refresh,    roles: PUBLIC_ACCESS }
        - { path: ^/api/register,         roles: PUBLIC_ACCESS }
        - { path: ^/api/login,            roles: PUBLIC_ACCESS }
        - { path: ^/api/cities,           roles: PUBLIC_ACCESS }
        - { path: ^/api/doc,              roles: PUBLIC_ACCESS }
        - { path: ^/api,                  roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/internal/api/tickets, roles: PUBLIC_ACCESS }
        - { path: ^/internal/api,         roles: ROLE_EMPLOYEE }
        - { path: ^/,                     roles: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm:   auto
                cost:        4
                time_cost:   3
                memory_cost: 10
