controllers:
    resource: ../src/Controller/
    type: annotation

api_controllers:
    resource: ../src/Api/Controller/
    type: annotation
    prefix: /api

external_api_controllers:
    resource: ../src/Api/External/Controller/
    type: annotation
    prefix: /external/api

internal_api_controllers:
    resource: ../src/Api/Internal/Controller/
    type: annotation
    prefix: /internal/api

kernel:
    resource: ../src/Kernel.php
    type: annotation
